### ISSUE TITLE
Develop branch

### ISSUE THREAD

**Issue by hkdobrev** [kurlltd/silex-doctrine-migrations-provider#10]
Could you clarify which branch should be used to base pull requests against? I see you are merging things to the `develop` branch, but the default branch of the repo is `master`.

Personally I don't see why you'd need both branches in a small repository such as this. For me the GitHub flow of merging into master and tagging releases from there is working fine.

Anyway, using the `develop` branch or not is up to you, but a clarification of what to base PRs against would be very welcome. Probably in `CONTRIBUTING.md`.

Thanks!

**Comment by breenie** [comment]
I have very little experience using PR based flow and don't really like having anything on master unless it's considered taggable. I'm happy with going with the flow though if it's easier to contribute.

**Comment by breenie** [comment]
Would making the default branch develop ease things?

**Comment by breenie** [comment]
I've made develop default.

**Comment by hkdobrev** [comment]
Thanks! This way the pull requests are based on develop by default and things like `closes #x` work out of the box when PRs are merged 😺
