### ISSUE TITLE
Symfony\Component\Console\Helper\DialogHelper not required

### ISSUE THREAD

**Issue by IMM0rtalis** [kurlltd/silex-doctrine-migrations-provider#14]
I installed dev-develop via composer and when I open the doctrine migrations-provider I get the message that Symfony\Component\Console\Helper\DialogHelper can not be found. 

Best,
Florian

**Comment by breenie** [comment]
Hi, what do you mean "when I open the doctrine migrations-provider"?

**Comment by breenie** [comment]
I see it now. Fixed in commit 6867960a5567dbdd0e3f5700d5dc0ebcba81b3e2.
