### ISSUE TITLE
Silex 2.x support

### ISSUE THREAD

**Issue by hkdobrev** [kurlltd/silex-doctrine-migrations-provider#6]
This service provider supports only Silex 1.x. It would be great if it's migrated to support Silex 2.x with the new structure of service providers.

**Comment by IMM0rtalis** [comment]
It is still not fetchable over composer in version 0.2. If you look the git-files tagged with 0.2 the old Silex\ServiceProviderInterface is still there...  

can you fix this please?

**Comment by hkdobrev** [comment]
@IMM0rtalis Hi! You could now use `0.2.1` where this should be addressed thanks to @breenie. Cheers!
