### ISSUE TITLE
Support Pimple 3.x without Silex

### ISSUE THREAD

**Issue by hkdobrev** [kurlltd/silex-doctrine-migrations-provider#9]
@breenie What do you think of supporting Pimple-only installation when Silex is not present? I think this is the recommended way as it's more portable and could be used in projects using Doctrine and Pimple without using Silex. That's why the service provider was moved from Silex to Pimple and also why Silex now publish their providers as a separate Composer package.

This means not using the `BootableProviderInterface`. We could move everything to `register()` and make things more lazy. Getting the configuration object would be lazy through Pimple. The only obstacle is adding the commands - if we add them in the register method then the configuration would be retrieved from the container before any option overriding from the user has been applied. So we could still add the commands in the `boot` method, but if you are not using Silex you'd just need to add the commands yourself or even better - call the boot method on the provider yourself and it'd add the commands for you.

How do you feel about that? Do you want me to make a PR with the described suggestions so we could discuss a concrete implementation?

**Comment by breenie** [comment]
@hkdobrev I've never used Pimple on it's own before so I'd have to believe what you say. Is there any documentation anywhere or examples where providers are built to support Pimple with and without Silex? 

Wouldn't registering the commands be a performance problem? Especially as it would be done every request and you're only going to want the migrations helper for console commands.

Shout me down if I've wrong but wouldn't it be easier and possibly better to have two service providers, one for Pimple and one for Silex?

**Comment by hkdobrev** [comment]
> I've never used Pimple on it's own before so I'd have to believe what you say. Is there any documentation anywhere or examples where providers are built to support Pimple with and without Silex?

Most of the Silex 2.x providers work without Silex.
- [DoctrineServiceProvider](https://github.com/silexphp/Silex-Providers/blob/master/DoctrineServiceProvider.php)
- [TwigServiceProvider](https://github.com/silexphp/Silex-Providers/blob/master/TwigServiceProvider.php)

Here's a simple provider I've made recently which works with Pimple, but also offers a trait for Silex: [ParsedownServiceProvider](https://github.com/clippings/parsedown-provider).

- [Pimple documentation about providers](http://pimple.sensiolabs.org/#extending-a-container)
- [Silex documentation about providers](http://silex.sensiolabs.org/doc/master/providers.html#creating-a-provider) which mentions to use only the API of Pimple so your provider could be used outside of Silex:

> The `Pimple\ServiceProviderInterface` belongs to the Pimple package, so take care to only use the API of `Pimple\Container` within your register method. Not only is this a good practice due to the way Pimple and Silex work, but may allow your provider to be used outside of Silex.

---

> Wouldn't registering the commands be a performance problem? Especially as it would be done every request and you're only going to want the migrations helper for console commands.

This provider would most likely be registered only in CLI when you have a Console application instance which it requires. So in most cases performance doesn't matter so much and requests won't be executed.

However we would still not register commands in the `register()` method. We would just lazy load the configuration in the `register()` method. We could still have a boot method to add the commands. Then the user could choose to either add the commands themselves or call the boot method. If using Silex, everything would be the same.

---

> Shout me down if I've wrong but wouldn't it be easier and possibly better to have two service providers, one for Pimple and one for Silex?

I don't think that's a practice given the state of the Silex providers from 2.x which I've seen. And I don't think that would help users of the provider who would be more confused than we are.

---

I'd try to put a quick PR up for you to review.

**Comment by hkdobrev** [comment]
@breenie If you want we could continue the discussion over a concrete implementation over at #12
